# Generated by Django 4.0.3 on 2022-03-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category_id',
            field=models.PositiveIntegerField(db_index=True, max_length=11, verbose_name='Name of Category'),
        ),
    ]
