# Generated by Django 4.0.3 on 2022-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_link',
            field=models.CharField(blank=True, db_index=True, max_length=5000, verbose_name='Trailer Link'),
        ),
    ]
