# Generated by Django 4.0.3 on 2022-03-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_type',
            field=models.CharField(choices=[('Newly Released', 'Newly Released'), ('Coming Soon', 'Coming Soon')], default='Newly Released', max_length=50, null=True, verbose_name='release_type'),
        ),
    ]
