# Generated by Django 4.0.3 on 2022-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category_id',
            field=models.IntegerField(db_index=True, verbose_name='Name of Category'),
        ),
    ]
